// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basic/resp.proto

package basic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RespBody struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	RespMsg              string   `protobuf:"bytes,2,opt,name=resp_msg,json=respMsg,proto3" json:"resp_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBody) Reset()         { *m = RespBody{} }
func (m *RespBody) String() string { return proto.CompactTextString(m) }
func (*RespBody) ProtoMessage()    {}
func (*RespBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30c96934fd22b05, []int{0}
}

func (m *RespBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBody.Unmarshal(m, b)
}
func (m *RespBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBody.Marshal(b, m, deterministic)
}
func (m *RespBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBody.Merge(m, src)
}
func (m *RespBody) XXX_Size() int {
	return xxx_messageInfo_RespBody.Size(m)
}
func (m *RespBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBody.DiscardUnknown(m)
}

var xxx_messageInfo_RespBody proto.InternalMessageInfo

func (m *RespBody) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespBody) GetRespMsg() string {
	if m != nil {
		return m.RespMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*RespBody)(nil), "basic.RespBody")
}

func init() { proto.RegisterFile("basic/resp.proto", fileDescriptor_c30c96934fd22b05) }

var fileDescriptor_c30c96934fd22b05 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4a, 0x2c, 0xce,
	0x4c, 0xd6, 0x2f, 0x4a, 0x2d, 0x2e, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x8b,
	0x28, 0x59, 0x72, 0x71, 0x04, 0xa5, 0x16, 0x17, 0x38, 0xe5, 0xa7, 0x54, 0x0a, 0x09, 0x71, 0xb1,
	0x24, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x92, 0x5c,
	0x1c, 0x20, 0x4d, 0xf1, 0xb9, 0xc5, 0xe9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xec, 0x20,
	0xbe, 0x6f, 0x71, 0x7a, 0x12, 0x1b, 0xd8, 0x20, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74,
	0xcf, 0x69, 0x3c, 0x5c, 0x00, 0x00, 0x00,
}
